# Generated by Django 5.0.9 on 2024-11-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('Firstname', models.CharField(max_length=150, null=True)),
                ('Middlename', models.CharField(max_length=150, null=True)),
                ('Lastname', models.CharField(max_length=150, null=True)),
                ('Mobile', models.IntegerField(null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Address', models.CharField(max_length=150, null=True)),
                ('Emergency', models.IntegerField(null=True)),
                ('Subject_Teacher', models.CharField(choices=[('M', 'Mathematics(general)'), ('E', 'English(general)'), ('C', 'Civic(general)'), ('B', 'Biology(general)'), ('CH', 'Chemistry(science)'), ('PY', 'Physics(civic)'), ('DP', 'Data-Processing(general)'), ('MK', 'Marketing(commercial)'), ('EC', 'Economic(general)'), ('COM', 'Computer-Studies(general)'), ('FM', 'Further-Math(science)'), ('GV', 'Government(art, commercial)'), ('LT', 'Literature(art)'), ('CM', 'Commerce(commercial)'), ('Ac', 'Accounting(commercial)'), ('HS', 'History(art)'), ('GG', 'Geography(science)'), ('C', 'Book-Keeping(science)'), ('Is', 'Islamic-Studies(general)'), ('Chr', 'Christain-Studies(general)'), ('TD', 'Technical-Drawing(science)')], max_length=5)),
                ('Class_Teacher', models.CharField(choices=[('J1', 'Jss1'), ('J2', 'Jss2'), ('J3', 'Js3'), ('S1', 'Ss1'), ('S2', 'Ss2'), ('S3', 'Ss3')], max_length=5)),
                ('DOB', models.DateTimeField()),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=150)),
                ('Cv', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
