# Generated by Django 5.0.9 on 2024-11-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Emergency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
