# Generated by Django 5.0.9 on 2024-12-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_tlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tlogin',
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Cv',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
