# Generated by Django 5.0.9 on 2024-12-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0008_teacher_ca1_teacher_ca2_teacher_ca3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('Firstname', models.CharField(max_length=150, null=True)),
                ('Middlename', models.CharField(max_length=150, null=True)),
                ('Lastname', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=250)),
                ('Mobile', models.IntegerField(null=True)),
                ('Department', models.CharField(choices=[('S', 'Science'), ('A', 'Art'), ('C', 'Commercial')], max_length=5)),
                ('Parent_Mobile', models.IntegerField()),
                ('Address', models.CharField(max_length=150, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Class', models.CharField(choices=[('J1', 'JsS1'), ('J2', 'Jss2'), ('J3', 'Jss3'), ('S1', 'SS1'), ('S2', 'Ss2'), ('S3', 'Ss3')], max_length=5)),
                ('DOB', models.DateTimeField()),
                ('Email', models.EmailField(max_length=100)),
                ('Admission_Number', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=150)),
            ],
        ),
    ]
