# Generated by Django 5.0.9 on 2024-12-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0009_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jss1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=350)),
                ('username', models.CharField(max_length=100)),
                ('schoolNo', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('LGA', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('parent_phone', models.CharField(max_length=100)),
                ('classs', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Jss2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=350)),
                ('username', models.CharField(max_length=100)),
                ('schoolNo', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('LGA', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('parent_phone', models.CharField(max_length=100)),
                ('classs', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Jss3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=350)),
                ('username', models.CharField(max_length=100)),
                ('schoolNo', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('LGA', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('parent_phone', models.CharField(max_length=100)),
                ('classs', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ss1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=350)),
                ('username', models.CharField(max_length=100)),
                ('schoolNo', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('LGA', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('parent_phone', models.CharField(max_length=100)),
                ('classs', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ss2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=350)),
                ('username', models.CharField(max_length=100)),
                ('schoolNo', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('LGA', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('parent_phone', models.CharField(max_length=100)),
                ('classs', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ss3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=350)),
                ('username', models.CharField(max_length=100)),
                ('schoolNo', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('LGA', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('parent_phone', models.CharField(max_length=100)),
                ('classs', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
