# Generated by Django 5.0.9 on 2024-12-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0010_jss1_jss2_jss3_ss1_ss2_ss3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jss1',
            name='LGA',
        ),
        migrations.RemoveField(
            model_name='jss1',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jss1',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='jss1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jss1',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='jss1',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='jss1',
            name='password',
        ),
        migrations.RemoveField(
            model_name='jss1',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='jss1',
            name='schoolNo',
        ),
        migrations.RemoveField(
            model_name='jss1',
            name='state',
        ),
        migrations.RemoveField(
            model_name='jss2',
            name='LGA',
        ),
        migrations.RemoveField(
            model_name='jss2',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jss2',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='jss2',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jss2',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='jss2',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='jss2',
            name='password',
        ),
        migrations.RemoveField(
            model_name='jss2',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='jss2',
            name='schoolNo',
        ),
        migrations.RemoveField(
            model_name='jss2',
            name='state',
        ),
        migrations.RemoveField(
            model_name='jss3',
            name='LGA',
        ),
        migrations.RemoveField(
            model_name='jss3',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jss3',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='jss3',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jss3',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='jss3',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='jss3',
            name='password',
        ),
        migrations.RemoveField(
            model_name='jss3',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='jss3',
            name='schoolNo',
        ),
        migrations.RemoveField(
            model_name='jss3',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ss1',
            name='LGA',
        ),
        migrations.RemoveField(
            model_name='ss1',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ss1',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='ss1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ss1',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='ss1',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='ss1',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ss1',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ss1',
            name='schoolNo',
        ),
        migrations.RemoveField(
            model_name='ss1',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ss2',
            name='LGA',
        ),
        migrations.RemoveField(
            model_name='ss2',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ss2',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='ss2',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ss2',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='ss2',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='ss2',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ss2',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ss2',
            name='schoolNo',
        ),
        migrations.RemoveField(
            model_name='ss2',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ss3',
            name='LGA',
        ),
        migrations.RemoveField(
            model_name='ss3',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ss3',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='ss3',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ss3',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='ss3',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='ss3',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ss3',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ss3',
            name='schoolNo',
        ),
        migrations.RemoveField(
            model_name='ss3',
            name='state',
        ),
        migrations.AddField(
            model_name='jss1',
            name='Admission_Number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss1',
            name='Class',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='jss1',
            name='Department',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='jss1',
            name='Firstname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss1',
            name='Gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jss1',
            name='Lastname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss1',
            name='Middlename',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss1',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jss1',
            name='Parent_Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jss1',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Admission_Number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Class',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Department',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Firstname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Lastname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Middlename',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Parent_Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Admission_Number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Class',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Department',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Firstname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Lastname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Middlename',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Parent_Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Admission_Number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Class',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Department',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Firstname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Lastname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Middlename',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Parent_Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Admission_Number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Class',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Department',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Firstname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Lastname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Middlename',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Parent_Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Admission_Number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Class',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Department',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Firstname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Lastname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Middlename',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Parent_Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='jss1',
            name='DOB',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jss1',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jss2',
            name='DOB',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jss2',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jss3',
            name='DOB',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jss3',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ss1',
            name='DOB',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ss1',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ss2',
            name='DOB',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ss2',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ss3',
            name='DOB',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ss3',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Admission_Number',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.CharField(choices=[('J1', 'JsS1'), ('J2', 'Jss2'), ('J3', 'Jss3'), ('S1', 'SS1'), ('S2', 'Ss2'), ('S3', 'Ss3')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='jss1',
            name='Address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss1',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jss1',
            name='Password',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jss2',
            name='Password',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jss3',
            name='Password',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ss1',
            name='Password',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ss2',
            name='Password',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ss3',
            name='Password',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
