# Generated by Django 5.0.9 on 2024-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0014_jss1_jss2_jss3_ss1_ss2_ss3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_level',
            field=models.CharField(choices=[('jss1', 'JSS1'), ('jss2', 'JSS2'), ('jss3', 'JSS3'), ('ss1', 'SS1'), ('ss2', 'SS2'), ('ss3', 'SS3')], max_length=5, null=True),
        ),
    ]
