# Generated by Django 5.0.9 on 2024-12-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0015_alter_student_class_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='ca1',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='ca2',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='ca3',
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
