# Generated by Django 5.0.9 on 2024-12-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0016_remove_teacher_ca1_remove_teacher_ca2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_disabled',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
