# Generated by Django 5.0.9 on 2024-12-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0021_alter_teacher_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Class_Teacher',
            field=models.CharField(blank=True, choices=[('J1', 'Jss1'), ('J2', 'Jss2'), ('J3', 'Js3'), ('S1', 'Ss1'), ('S2', 'Ss2'), ('S3', 'Ss3')], max_length=5, null=True),
        ),
    ]
