# Generated by Django 5.0.9 on 2024-12-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0022_alter_teacher_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('department', models.CharField(choices=[('S', 'Science'), ('A', 'Art'), ('C', 'Commercial')], max_length=1)),
            ],
        ),
    ]
