# Generated by Django 5.0.9 on 2024-12-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0024_department_alter_subject_name_alter_teacher_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('S', 'Science'), ('A', 'Art'), ('C', 'Commercial')], max_length=50, unique=True),
        ),
    ]
