# Generated by Django 5.0.9 on 2024-12-17 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0026_alter_subject_department_student_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jss1',
            name='department',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='jss1',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='jss2',
            name='department',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='jss2',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='jss3',
            name='department',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='jss3',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='ss1',
            name='department',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ss1',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='ss2',
            name='department',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ss2',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='ss3',
            name='department',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ss3',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Science', 'Science'), ('Art', 'Art'), ('Commercial', 'Commercial')], max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Mal', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(choices=[('Science', 'Science'), ('Art', 'Art'), ('Commercial', 'Commercial')], on_delete=django.db.models.deletion.CASCADE, related_name='subject_department', to='mapp.student'),
        ),
    ]
